services:
  books:  
    image: lorentzimys/books-service:latest
    environment:
      - PORT=6000
      - COUNTER_SERVICE_HOST=books-counter
      - COUNTER_SERVICE_PORT=6010
    ports:
      - 80:6000
    depends_on:
      - books-counter

  storage:
    image: redis:alpine
    volumes:
      - ./redis:/data

  books-counter:
    build: ./booksCounterService
    environment:
      - PORT=6010
      - REDIS_HOST=storage
    ports:
      - "6010:6010" 
    depends_on:
      - storage

  